### ISSUE TITLE
 JPEG support not compiled. Please install the libjpeg development package before building.

### ISSUE THREAD

**Issue by xuanjinliang** [imagemin/cwebp-bin#11]
centos

{ [Error: Command failed: /usr/local/node_4.4.4.3/lib/node_modules/fis-postpackager-jpgtowebp/node_modules/cwebp-binLocal/vendor/linux/x64/cwebp /data1/htdocs/m.fanxing.com/static/mobile/520Activity/images/img_4.jpg -o /data1/htdocs/m.fanxing.com/staticPub/images/_f469d98.webp
JPEG support not compiled. Please install the libjpeg development package before building.
Error! Could not process file /data1/htdocs/m.fanxing.com/static/mobile/520Activity/images/img_4.jpg
Error! Cannot read input picture file '/data1/htdocs/m.fanxing.com/static/mobile/520Activity/images/img_4.jpg'
]
  killed: false,
  code: 255,
  signal: null,
  cmd: '/usr/local/node_4.4.4.3/lib/node_modules/fis-postpackager-jpgtowebp/node_modules/cwebp-binLocal/vendor/linux/x64/cwebp /data1/htdocs/m.fanxing.com/static/mobile/520Activity/images/img_4.jpg -o /data1/htdocs/m.fanxing.com/staticPub/images/_f469d98.webp' }

**Comment by shinnn** [comment]
https://developers.google.com/speed/webp/docs/precompiled

Read the `Note (for Linux and Mac OS X):` section.
