### ISSUE TITLE
Couldn't access Windows Imaging Component

### ISSUE THREAD

**Issue by yangg** [imagemin/cwebp-bin#12]
Hi, I'm running [imagemin-webp](https://github.com/imagemin/imagemin-webp) on Windows 7, it throws an erorr
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: CoCreateInstance(MAKE_REFGUID(CLSID_WICImagingFactory), NULL, CLSCTX_INPR                                                                                            OC_SERVER, MAKE_REFGUID(IID_IWICImagingFactory), (LPVOID*)&factory) failed 80040                                                                                            154
Couldn't access Windows Imaging Component (are you running Windows XP SP3 or new                                                                                            er?). Most formats not available. Use -s for the available YUV input.
Decoding of input data failed.
Status: 3(BITSTREAM_ERROR)
Error! Could not process file C:\Users\ADMINI~1\AppData\Local\Temp\d49c283e-4e92                                                                                            -4a6d-a557-1a982d084787
Error! Cannot read input picture file 'C:\Users\ADMINI~1\AppData\Local\Temp\d49c                                                                                            283e-4e92-4a6d-a557-1a982d084787'

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\juanpi_code\actstatic\node_modules\cross-spawn-a                                                                                            sync\lib\enoent.js:37:29)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```
> Couldn't access Windows Imaging Component (are you running Windows XP SP3 or new                                                                                            er?)

But i'm running it on windows 7.
I'v googled a lot , but cannot find an answer.

**Comment by shinnn** [comment]
Just upgrade to Windows 10. windows 7 is not actively maintained.

**Comment by TheDrive2** [comment]
Same problem with the console dwebp.exe and Win7 Starter x86
Isn't it simple to include fine sharpened for the decades free png/jpg related libs directly to the project?
Why to use 3rd party dependencies in the simplest component related to the main functionality?
Isn't it simple to fix your own project neither advice many ppl to upgrade monster spyware OS's?
It's common problem just look using Google search for the error message.
And I do use XP for many PC and Win9x (and DOS and Linux/BSD too) for some and will still use it... Works fine unless some 'super technology' for the primitive console util isn't req'd... Let's fill the world with love and intellect, not the laziness and ugly techs, Thanks.

**Comment by TheDrive2** [comment]
And next when I converted same webp images to the bmp many apps could not open them claiming it's not an image at all however BM6 image header is in the place. At the same time Chrome shows bmp and the original webp pics w/o any problems. Got these images from an Android phone. They are 576x1024 24bpp.
BMP is a simplest format w/o any compression (unless RLE is used). Never seen any compatibility problems with it since early 90's. WTF?

Will you advice me to use Chrome as an images viewer or there is a way to use standard images format supported by all these utils written for about a 30 years? Some do start and show me an image in a less then a second, including HiRes and highly compressed ones.

**Comment by TheDrive2** [comment]
And finally found and used XnConvert util.
It does correctly convert either to the png either to the bmp.
Bmp files have the same size and similar binary header but absolutely another bit encoding inside.
And there is no problem to open them with any app,

**Comment by TheDrive2** [comment]
Examples
