### ISSUE TITLE
0.6.0 available

### ISSUE THREAD

**Issue by jeromedecoster** [imagemin/cwebp-bin#14]
Hi,

cwebp 0.6.0 is available
https://chromium.googlesource.com/webm/libwebp/

Also it can be nice to have **gif2webp** or **webpmux** binaries available to convert gif to animated webp with imagemin
https://developers.google.com/speed/webp/docs/gif2webp
https://developers.google.com/speed/webp/docs/webpmux

Regards!

**Comment by sindresorhus** [comment]
> Also it can be nice to have gif2webp or webpmux binaries available to convert gif to animated webp with imagemin
developers.google.com/speed/webp/docs/gif2webp
developers.google.com/speed/webp/docs/webpmux

Those should be separate binary packages. Not something we need here, but you could easily fork this repo and modify it to work with those.
