### ISSUE TITLE
Update `bin-build` to version 3.0.0

### ISSUE THREAD

**Issue by noahbrenner** [imagemin/cwebp-bin#20]
The dependency chain from the current `bin-build@2.2.0` dependency includes `gulp-util`, which is deprecated, but `bin-build@3.0.0` does not have that issue. I know there is a major version change to account for, so it would be more work than just a version bump, but it would be great to get this updated, if possible.

I'm a bit busy this week, but if you'd prefer a pull request, I can work on one when I find some time.

Thanks so much!

**Comment by QuentinCurtet** [comment]
I think the problem is the same for bin-wrapper no ?

**Comment by rejas** [comment]
Added the update to my PR: https://github.com/imagemin/cwebp-bin/pull/24
