### ISSUE TITLE
Error: cwebp-bin@4.0.0 postinstall

### ISSUE THREAD

**Issue by Jelle-vz** [imagemin/cwebp-bin#22]
Problem with npm install.

npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (...\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (...\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

As far as i can tell this is solved by the pullrequest in https://github.com/imagemin/cwebp-bin/pull/21. 
This only fails on a syntax issue for Node4. Can we get this fixed?

**Comment by guilhermehn** [comment]
#21 was closed in favor of #24, which was merged 3 days ago.

@1000ch @sindresorhus When will the next version be released?

**Comment by svewag** [comment]
> When will the next version be released?

+1

**Comment by 1000ch** [comment]
Please try [v5.0.0](https://github.com/imagemin/cwebp-bin/releases/tag/v5.0.0).
