### ISSUE TITLE
cwebp error

### ISSUE THREAD

**Issue by livissnack** [imagemin/cwebp-bin#32]
⚠ Command failed: /var/www/doniai/production/source/node_modules/cwebp-bin/vendor/cwebp -version
/var/www/doniai/production/source/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libXi.so.6: cannot open shared object file: No such file or directory

  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✖ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17)

**Comment by budimirbudimir** [comment]
Having a similar issue as of today:

> cwebp-bin@5.0.0 postinstall /usr/src/app/node_modules/cwebp-bin
> node lib/install.js

  ⚠ Command failed: /usr/src/app/node_modules/cwebp-bin/vendor/cwebp -version
/usr/src/app/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
Too long with no output (exceeded 10m0s)

**Comment by RicoLiu** [comment]
Same issue

**Comment by MSafyan** [comment]
Same issue

**Comment by 1000ch** [comment]
This seems to be caused by the dependency problem. Would you try to install again regarding [Compiling the utility instruction](https://developers.google.com/speed/webp/docs/compiling)?
