### ISSUE TITLE
cwebp pre-build test failed

### ISSUE THREAD

**Issue by RicoLiu** [imagemin/cwebp-bin#40]
Jenkins log:
```
⚠ connect ETIMEDOUT 151.101.228.133:443
⚠ cwebp pre-build test failed
ℹ compiling from source
✔ cwebp built successfully
```

**Comment by aslkami** [comment]
‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ cwebp pre-build test failed
  i compiling from source

gatsby npm install smothing wrong

**Comment by Giwan** [comment]
@aslkami I had the same issue. The fix that worked for me was to update all of the outdated components. 

```
npm upgrade
```

After that fix all of the vulnerabilities. 
```
npm audit fix
```

**Comment by 1000ch** [comment]
It is difficult to support all platforms by bundled pre-built binaries, this is one of the reasons the compiling from source is provided.

**Comment by im-variable** [comment]
how can i solve this issue in yarn 

```
[4/4] Rebuilding all packages...
[-/4] ⠐ waiting...
[-/4] ⠐ waiting...
[3/4] ⠐ mozjpeg
error E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin
Output:
connect ETIMEDOUT 2405:200:1607:2820:41::36:443
cwebp pre-build test failed
compiling from source
cwebp built successfully
E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\bin-build\node_modules\execa\index.js:231
                                err = new Error(`Command failed: ${joinedCmd}${output}`);
                                      ^

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --disable-shared --prefix="E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin\vendor" --bindir="E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin\vendor""
'.' is not recognized as an internal or external command,
operable program or batch file.

    at E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\bin-build\node_modules\execa\index.js:231:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0) {
  code: 1,
  killed: false,
  stdout: '',
  stderr: "'.' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n',
  failed: true,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "./configure --disable-shared --prefix="E:\\XXXXXXXXXXXXXX\\XXXXXXXXXXXXXX\\node_modules\\cwebp-bin\\vendor" --bindir="E:\\XXXXXXXXXXXXXX\\XXXXXXXXXXXXXX\\node_modules\\cwebp-bin\\vendor""',
  timedOut: false
}
```

**Comment by adoin** [comment]
> how can i solve this issue in yarn
> 
> ```
> [4/4] Rebuilding all packages...
> [-/4] ⠐ waiting...
> [-/4] ⠐ waiting...
> [3/4] ⠐ mozjpeg
> error E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin: Command failed.
> Exit code: 1
> Command: node lib/install.js
> Arguments:
> Directory: E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin
> Output:
> connect ETIMEDOUT 2405:200:1607:2820:41::36:443
> cwebp pre-build test failed
> compiling from source
> cwebp built successfully
> E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\bin-build\node_modules\execa\index.js:231
>                                 err = new Error(`Command failed: ${joinedCmd}${output}`);
>                                       ^
> 
> Error: Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --disable-shared --prefix="E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin\vendor" --bindir="E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\cwebp-bin\vendor""
> '.' is not recognized as an internal or external command,
> operable program or batch file.
> 
>     at E:\XXXXXXXXXXXXXX\XXXXXXXXXXXXXX\node_modules\bin-build\node_modules\execa\index.js:231:11
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Promise.all (index 0) {
>   code: 1,
>   killed: false,
>   stdout: '',
>   stderr: "'.' is not recognized as an internal or external command,\r\n" +
>     'operable program or batch file.\r\n',
>   failed: true,
>   signal: null,
>   cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "./configure --disable-shared --prefix="E:\\XXXXXXXXXXXXXX\\XXXXXXXXXXXXXX\\node_modules\\cwebp-bin\\vendor" --bindir="E:\\XXXXXXXXXXXXXX\\XXXXXXXXXXXXXX\\node_modules\\cwebp-bin\\vendor""',
>   timedOut: false
> }
> ```

Same as your situation, any solution?
