### ISSUE TITLE
Issue with bright hues image conversion

### ISSUE THREAD

**Issue by Amber-Williams** [imagemin/cwebp-bin#46]
I haven't noticed much color loss with cweb-bin until using brighter hues like this pink in both JPG's and PNG's there tends to be some loss of color

This is the original
![image](https://user-images.githubusercontent.com/27780374/90874754-0b291f80-e398-11ea-9a98-235e16c42ee0.png)

This is the WebP
![image](https://user-images.githubusercontent.com/27780374/90874830-27c55780-e398-11ea-8bbd-9e86cf7fac12.png)

**Comment by 1000ch** [comment]
@Amber-Williams 
I think this is not caused by this package because this is just a npm wrapper. Could you consider trying it with another configuration or issuing on [the official places](https://developers.google.com/speed/webp/community)?
