### ISSUE TITLE
windows '.' is not recognized as an internal or external command npm run

### ISSUE THREAD

**Issue by kiloc** [imagemin/cwebp-bin#61]
![image](https://user-images.githubusercontent.com/16029014/226272847-023dade8-bd48-4733-a1b1-be6b9c05160b.png)
![image](https://user-images.githubusercontent.com/16029014/226273114-e9b3d8bb-3805-43cf-b89f-9b063dc5092a.png)

**Comment by kiloc** [comment]
![image](https://user-images.githubusercontent.com/16029014/226284986-a52781d3-38ba-414c-870b-14681cc1fc1e.png)
 fixed, because this file can't download in China

**Comment by adoin** [comment]
> ![image](https://user-images.githubusercontent.com/16029014/226284986-a52781d3-38ba-414c-870b-14681cc1fc1e.png) fixed, because this file can't download in China

那要咋下啊

**Comment by adoin** [comment]
> ![image](https://user-images.githubusercontent.com/16029014/226284986-a52781d3-38ba-414c-870b-14681cc1fc1e.png) fixed, because this file can't download in China

我下的这个库里面的1.2.1，还是报错的。。。
